# Generated by Django 3.2.25 on 2024-08-27 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piscina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profundidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('forma', models.CharField(choices=[('retangular', 'Retangular'), ('circular', 'Circular')], max_length=50)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piscinas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
